train:
val:
save_path:
model : resnet34
weights: None
batch_size: 8
image_size: 640
num_classes: 5
class_names: [
        'DJIAVATA2',
        'DJIFPVCOMBO',
        'DJIMAVIC3PRO',
        'DJIMINI3',
        'DJIMINI4PRO',
]
device: 'cuda'
num_epochs: 150
shuffle: True
lr: 0.000001
optimizer: None
