train: E:\Drone_dataset\RFUAV\exp3\train
val: E:\Drone_dataset\RFUAV\exp3\valid
save_path: E:\Drone_dataset\RFUAV\exp3\res
model : resnet101
weights: None
batch_size: 8
image_size: 640
num_classes: 7
class_names: [
        'DJMAVIC3PRO',
        'DJMINI3',
        'DJMINI4PRO',
        'empty',
        'FLYSKY_FS_I6X',
        'Radiolink_AT9S_Pro',
        'FutabaT14SG',
]
device: 'cuda'
num_epochs: 150
shuffle: True
lr: 0.00001
optimizer: None
